# Generated by Django 5.1.3 on 2024-12-14 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_remove_admin_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='member',
            name='intrest_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='paid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='skipped_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='total_invoice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='unpaid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='loan_id',
            field=models.CharField(unique=True),
        ),
    ]
