# Generated by Django 5.1.3 on 2024-12-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_member_balance_amount_member_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='total_invoice',
        ),
    ]
