# Generated by Django 5.1.3 on 2024-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_remove_member_total_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
