# Generated by Django 5.1.3 on 2024-12-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_member_recovery_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='paid_days',
        ),
        migrations.RemoveField(
            model_name='member',
            name='unpaid_days',
        ),
    ]
