# Generated by Django 5.1.3 on 2024-12-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0011_member_daily_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='daily_interest_rate',
        ),
        migrations.RemoveField(
            model_name='member',
            name='recovery_amount',
        ),
    ]
