# Generated by Django 5.1.3 on 2024-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0012_remove_member_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='recovery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
