# Generated by Django 5.1.3 on 2024-12-24 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0013_member_balance_amount_member_recovery_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='intrest_amount',
            new_name='interest_amount',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='loan_disberment_amount',
            new_name='loan_disbursement_amount',
        ),
        migrations.AddField(
            model_name='member',
            name='daily_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5),
        ),
        migrations.AddField(
            model_name='member',
            name='paid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='total_days',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='member',
            name='unpaid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_code',
            field=models.CharField(default='satish123', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='loan_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
