# Generated by Django 5.1.3 on 2024-12-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0014_rename_intrest_amount_member_interest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='paid_days',
        ),
        migrations.RemoveField(
            model_name='member',
            name='recovery_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='unpaid_days',
        ),
    ]
